
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks: 
      - app-network
    environment:
      - DB_HOST=newdb.clushmnnhufs.us-west-2.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=survey
networks:
  app-network:
    driver: bridge

